name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: ca-central-1
  S3BUCKET: codedeploystack-webappdeploymentbucket-5ff3rfqc68zm 


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
          
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-python-api --s3-bucket codedeploystack-webappdeploymentbucket-5ff3rfqc68zm --capabilities CAPABILITY_IAM --region ca-central-1 
