on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: IAMROLE_GITHUB
          aws-secret-access-key: ${{ secrets.IAMROLE_GITHUB }}
          #role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          #role-session-name: GitHub-Action-Role
          aws-region: ca-central-1
          
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-python-api --s3-bucket codedeploystack-webappdeploymentbucket-5ff3rfqc68zm --capabilities CAPABILITY_IAM --region ca-central-1 
